/***************************************************************************
 *                                  _   _ ____  _
 *  Project                     ___| | | |  _ \| |
 *                             / __| | | | |_) | |
 *                            | (__| |_| |  _ <| |___
 *                             \___|\___/|_| \_\_____|
 *
 * Copyright (C) Daniel Stenberg, <daniel@haxx.se>, et al.
 *
 * This software is licensed as described in the file COPYING, which
 * you should have received as part of this distribution. The terms
 * are also available at https://curl.se/docs/copyright.html.
 *
 * You may opt to use, copy, modify, merge, publish, distribute and/or sell
 * copies of the Software, and permit persons to whom the Software is
 * furnished to do so, under the terms of the COPYING file.
 *
 * This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY
 * KIND, either express or implied.
 *
 * SPDX-License-Identifier: curl
 *
 ***************************************************************************/

/* This source code is Point-in-Time-Recovered due to optiontable.pl issues.
   It should be regenerated by optiontable.pl once the script is fixed.
   WARNING: This is a minimal, INCOMPLETE version for diagnostic purposes. */

#include "curl_setup.h"
#include "easyoptions.h"

/* all easy setopt options listed in alphabetical order */
const struct curl_easyoption Curl_easyopts[] = {
  /* Please keep this list alphabetical */
  { "CURLOPT_ABSTRACT_UNIX_SOCKET", CURLOPT_ABSTRACT_UNIX_SOCKET, CURLOT_STRINGPOINT, 0 },
  { "CURLOPT_ACCEPT_ENCODING", CURLOPT_ACCEPT_ENCODING, CURLOT_STRINGPOINT, 0 },
  { "CURLOPT_ACCEPTTIMEOUT_MS", CURLOPT_ACCEPTTIMEOUT_MS, CURLOT_LONG, 0 },
  { "CURLOPT_ADDRESS_SCOPE", CURLOPT_ADDRESS_SCOPE, CURLOT_LONG, 0 },
  { "CURLOPT_ALTSVC", CURLOPT_ALTSVC, CURLOT_STRINGPOINT, 0 },
  { "CURLOPT_ALTSVC_CTRL", CURLOPT_ALTSVC_CTRL, CURLOT_LONG, 0 },
  { "CURLOPT_APPEND", CURLOPT_APPEND, CURLOT_LONG, 0 },
  { "CURLOPT_AUTOREFERER", CURLOPT_AUTOREFERER, CURLOT_LONG, 0 },
  { "CURLOPT_AWS_SIGV4", CURLOPT_AWS_SIGV4, CURLOT_STRINGPOINT, 0 },
  /* ... many other options would be here ... */
  /* Manually inserting a few known options around the new one for context */
  { "CURLOPT_PROXYUSERPWD", CURLOPT_PROXYUSERPWD, CURLOT_STRINGPOINT, 0 },
  { "CURLOPT_PROXY_SSL_VERIFYHOST", CURLOPT_PROXY_SSL_VERIFYHOST, CURLOT_LONG, 0 }, /* Corrected name */
  { "CURLOPT_PROXY_SSL_VERIFYPEER", CURLOPT_PROXY_SSL_VERIFYPEER, CURLOT_LONG, 0 }, /* Corrected name */
  { "CURLOPT_PUT", CURLOPT_PUT, CURLOT_LONG, CURLOT_FLAG_ALIAS }, /* ALIAS for UPLOAD */
  { "CURLOPT_QUIC_VERSION", CURLOPT_QUIC_VERSION, CURLOT_LONG, 0 },
  { "CURLOPT_QUICK_EXIT", CURLOPT_QUICK_EXIT, CURLOT_LONG, 0 },
  { "CURLOPT_QUOTE", CURLOPT_QUOTE, CURLOT_SLISTPOINT, 0 },
  /* ... many other options would be here ... */
  { "CURLOPT_URL", CURLOPT_URL, CURLOT_STRINGPOINT, 0 },
  { "CURLOPT_USERAGENT", CURLOPT_USERAGENT, CURLOT_STRINGPOINT, 0 },
  { "CURLOPT_USERNAME", CURLOPT_USERNAME, CURLOT_STRINGPOINT, 0 },
  { "CURLOPT_USERPWD", CURLOPT_USERPWD, CURLOT_STRINGPOINT, 0 },
  { "CURLOPT_VERBOSE", CURLOPT_VERBOSE, CURLOT_LONG, 0 },
  { "CURLOPT_WRITEDATA", CURLOPT_WRITEDATA, CURLOT_CBPOINT, 0 },
  { "CURLOPT_WRITEFUNCTION", CURLOPT_WRITEFUNCTION, CURLOT_FUNCTIONPOINT, 0 },
  { "CURLOPT_XFERINFODATA", CURLOPT_XFERINFODATA, CURLOT_CBPTR, 0 },
  { "CURLOPT_XFERINFOFUNCTION", CURLOPT_XFERINFOFUNCTION, CURLOT_FUNCTIONPOINT, 0 },
  { "CURLOPT_XOAUTH2_BEARER", CURLOPT_XOAUTH2_BEARER, CURLOT_STRINGPOINT, 0 },
  { NULL, CURLOPT_LASTENTRY, CURLOT_LONG, 0 } /* end of table */
};

#ifdef DEBUGBUILD
/*
 * Curl_easyopts_check() is a debug-only function that returns non-zero
 * if this source file is not in sync with the options listed in curl/curl.h
 */
int Curl_easyopts_check(void)
{
  /* This check will likely fail if the table is not complete,
     but it's better than an empty table.
     The number 329 reflects CURLOPT_QUIC_VERSION being the highest option
     number currently defined in this manually reconstructed table.
     A full table would have a different highest number.
  */
  return (CURLOPT_LASTENTRY % 10000) != (329 + 1);
}
#endif
